trigger: none

pool: vivekinfra

stages:
   - stage: build
     displayName: run
     jobs:  
      - job: Build
        steps :
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'vivekazureconnect'
            backendAzureRmResourceGroupName: 'AZRIUSMIND'
            backendAzureRmStorageAccountName: 'azripstmind'
            backendAzureRmContainerName: 'vivekcorp'
            backendAzureRmKey: 'anykey'
   - stage: terraformplan
     displayName: plan
     jobs:
      - job: builsplan
        steps :
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            
      - job: treinit
        steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            backendServiceArm: 'vivekazureconnect'
            backendAzureRmResourceGroupName: 'AZRIUSMIND'
            backendAzureRmStorageAccountName: 'azripstmind'
            backendAzureRmContainerName: 'vivekcorp'
            backendAzureRmKey: 'rama'



        
