trigger: none

pool: vivekinfra

stages:
   - stage: build
     displayName: run
     jobs:  
      - job: Build
        steps :
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/RG'
            backendServiceArm: 'vivekazureconnect'
            backendAzureRmResourceGroupName: 'AZRIUSMIND'
            backendAzureRmStorageAccountName: 'azripstmind'
            backendAzureRmContainerName: 'vivekcorp'
            backendAzureRmKey: 'anykey'
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/RG'
            environmentServiceNameAzureRM: 'vivekazureconnect'
            
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/RG'
            environmentServiceNameAzureRM: 'vivekazureconnect'
        



        
