name: RG

on:
  workflow_dispatch:
  push:
    branches:
      - none

permissions:
  id-token: write
  contents: read

jobs:
  create-resource-group:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure using OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: 1.5.7

    - name: Terraform init
      working-directory: ./RG
      run: terraform init

    - name: Terraform validate
      working-directory: ./RG
      run: terraform validate

    - name: Terraform plan
      working-directory: ./RG
      run: terraform plan
          
    - name: Terraform apply
      working-directory: ./RG
      run: terraform apply

      
